version: "3.7"
services:
  monitoring:
    image: $MONITORING_SERVICE_IMG
    container_name: monitoring_service
    restart: on-failure
    volumes:
      - ../data:/monitoring_service/data
      - ../data_sources:/monitoring_service/data_sources
    command: python src/monitoring_service.py --port=$MONITORING_SERVICE_PORT
    ports:
      - $MONITORING_SERVICE_PORT:$MONITORING_SERVICE_PORT
